spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/CodeRush
    username: postgres
    password: 2060kleim2070
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        id:
          new_generator_mappings: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type: trace
    root: info

server:
  port: 8081
  servlet:
    context-path: /